name: todo_list
description: Excercise 2 - Advanced Mobile Development course.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  json_annotation: ^4.7.0
  equatable: ^2.0.5
  sqflite: ^2.2.0+2
  intl: ^0.17.0
  flutter_slidable: ^2.0.0
  logger: ^1.1.0
  path_provider: ^2.0.11
  flutter_easyloading: ^3.0.5
  flutter_datetime_picker: ^1.5.1
  flutter_local_notifications: ^12.0.3
  timezone: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true